
name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: echo
      run: echo 'Something was pushed'
    - name: make
      run: make

    - name: make test
      run: pip install -U platformio && platform update && make test
    - name: make clean
      run: make clean
