name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: echo
      run: echo 'Something was pushed'
    - name: make
      run: make
    - name: make test
      run: make test
    - name: make clean
      run: make clean
      
# Below is some stuff from my example and also not from my example.
#    - name: kompilera
#      run: gcc main.c -o main
#    - name: run_program
#      run: ./main
#    - name: configure
#      run: ./configure
#    - name: make
#      run: make
#    - name: make check
#      run: make check
#    - name: make distcheck
#      run: make distcheck
