
name: C/C++ CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: make test
      run: apt-get install python3-setuptools && pip3 install -U platformio && platform update && make test
    - name: make clean
      run: make clean
